# Ruby is our language as asciidoctor is a ruby gem.
lang: node_js
script:
  - npm install && npm run build
  # This will ensure a commit even if there are no changes to deployed version
  # Hence, the database will be re-seeded.
  - echo $TRAVIS_BUILD_NUMBER > test.txt
after_success:
  - .travis/push.sh
